{% set name = "querystring_parser" %}
{% set version = "1.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 644fce1cffe0530453b43a83a38094dbe422ccba8c9b2f2a1c00280e14ca8a62

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - six

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - querystring_parser

about:
  home: https://github.com/bernii/querystring-parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: QueryString parser for Python/Django that correctly handles nested dictionaries
  dev_url: https://github.com/bernii/querystring-parser

extra:
  recipe-maintainers:
    - jaroslawk
    - paulmelnikow
    - xhochy
